export default status = [
  { id: 1, name: 'At Work', image: 'placeholder' },
  { id: 2, name: 'Studying', image: 'placeholder' },
  { id: 3, name: 'Reading', image: 'placeholder' },
  { id: 4, name: 'Homework', image: 'placeholder' },
  { id: 5, name: 'In Classes', image: 'placeholder' },
  { id: 6, name: 'Sleeping', image: 'placeholder' },
  { id: 7, name: 'Eating', image: 'placeholder' },
  { id: 8, name: 'Resting', image: 'placeholder' },
  { id: 9, name: 'Exercising', image: 'placeholder' },
  { id: 10, name: 'Doing Chores', image: 'placeholder' },
  { id: 11, name: 'Running errands', image: 'placeholder' },
  { id: 12, name: 'Cooking', image: 'placeholder' },
  { id: 13, name: 'Shopping', image: 'placeholder' },
  { id: 14, name: 'Travelling', image: 'placeholder' },
  { id: 15, name: 'Relaxing', image: 'placeholder' },
  { id: 16, name: 'Playing Games', image: 'placeholder' },
  { id: 17, name: 'Watching Shows', image: 'placeholder' },
  { id: 18, name: 'Listening to music', image: 'placeholder' },
  { id: 19, name: 'Celebrating', image: 'placeholder' },
  { id: 20, name: 'Thinking', image: 'placeholder' },
  { id: 21, name: 'Daydreaming', image: 'placeholder' },
  { id: 22, name: 'Idle', image: 'placeholder' },
  { id: 23, name: 'Sitting quietly', image: 'placeholder' },
  { id: 24, name: 'Zoning out', image: 'placeholder' },
  { id: 25, name: 'Procrastinating', image: 'placeholder' },
  { id: 26, name: 'Scrolling', image: 'placeholder' },
  { id: 27, name: 'Waiting For You', image: 'placeholder' },
  { id: 28, name: 'Sad', image: 'placeholder' },
  { id: 29, name: 'Depressed', image: 'placeholder' },
  { id: 30, name: 'Tired', image: 'placeholder' },
  { id: 31, name: 'Happy', image: 'placeholder' },
  { id: 32, name: 'Sick', image: 'placeholder' }
];